version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN --domain-owner $AWS_ACCOUNT_ID --query authorizationToken --output text`
      - export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
      - cp maven-settings.xml ~/.m2/settings.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
